language: cpp
sudo: false
dist: trusty

compiler:
  - clang
  - gcc
  
before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX

script:
  - cmake .
  - cmake --build .
  - ctest -VV --output-on-failure